// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwDWaFltuq5kPWeRn14biWaa7SCY5-Ck',
    appId: '1:470165331852:web:080f5603dd0d0f5e0b80a9',
    messagingSenderId: '470165331852',
    projectId: 'my-proyect-b2d79',
    authDomain: 'my-proyect-b2d79.firebaseapp.com',
    storageBucket: 'my-proyect-b2d79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3rPXEDLlXgM3o7JPsad8PqD3Er0ssSs',
    appId: '1:470165331852:android:75bb9002aa1e08fe0b80a9',
    messagingSenderId: '470165331852',
    projectId: 'my-proyect-b2d79',
    storageBucket: 'my-proyect-b2d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2t-u6xwii1EOeGqHokL-4diobuSSdAC8',
    appId: '1:470165331852:ios:57b6f54e6df562780b80a9',
    messagingSenderId: '470165331852',
    projectId: 'my-proyect-b2d79',
    storageBucket: 'my-proyect-b2d79.appspot.com',
    iosClientId: '470165331852-rb3ijb79ee7emdjfsv5jn2npp1rgvcl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProyect',
  );
}
